// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeIRCNick(arg1:string):Promise<void>;

export function CoinInfo():Promise<Record<string, any>>;

export function ConnectIRC():Promise<void>;

export function GetBalance():Promise<Record<string, any>>;

export function GetBlockchainInfo():Promise<Record<string, any>>;

export function GetIRCMessages():Promise<Array<Record<string, any>>>;

export function GetIRCStatus():Promise<Record<string, any>>;

export function GetIRCUsers():Promise<Array<string>>;

export function GetPeerCount():Promise<number>;

export function GetSyncProgress():Promise<number>;

export function GetWalletAddress():Promise<string>;

export function SendIRCMessage(arg1:string):Promise<void>;

export function SetMining(arg1:boolean):Promise<void>;
