blank_issues_enabled: false
contact_links:
  - name: Questions & Discussion
    url: https://github.com/bams-repo/go-chain/discussions
    about: Ask questions, share ideas, or discuss Fairchain in our community Discussions.
